#!/bin/sh
#deploy="false"
deploy="true"

image=ramana
version=1.0-SNAPSHOT
latest=true

#OPTIONS="--no-cache --force-rm"
#OPTIONS="--no-cache"
#OPTIONS="--force-rm"
OPTIONS=""

docker build ${OPTIONS} -t hello/${image}:1.0-SNAPSHOT .
if [ "$?" -eq 0 ] && [ ${deploy} == "true" ]; then
    docker push hello/${image}:1.0-SNAPSHOT
    if [ "$latest" == "true" ]; then
        docker tag hello/${image}:1.0-SNAPSHOT hello/${image}:latest
        docker push hello/${image}:latest
    fi
fi